# Generated by Django 2.2.5 on 2019-09-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20190925_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicture',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_type',
            field=models.CharField(default='Actor', max_length=15),
        ),
    ]
