# Generated by Django 2.2.5 on 2019-09-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_auto_20190930_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
