# Generated by Django 2.2.5 on 2019-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_auto_20190930_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
