# Generated by Django 2.2.5 on 2019-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPicture',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('mp_type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=140)),
                ('genre', models.CharField(max_length=15)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_type', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(to='movieapp.MotionPicture')),
            ],
        ),
    ]
