# Generated by Django 2.2.5 on 2019-11-05 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 11, 5)),
        ),
    ]
