# Generated by Django 2.2.5 on 2019-10-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
