# Generated by Django 2.2.5 on 2019-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_motionpicture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionpicture',
            name='mp_type',
            field=models.CharField(default='Movie', max_length=15),
        ),
    ]
