# Generated by Django 2.2.5 on 2019-11-07 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20191105_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_date_time', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/barcodes/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='categorylabel',
            name='category',
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 11, 7)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryLabel',
        ),
    ]
