# Generated by Django 2.2.5 on 2019-11-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20191107_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='image',
            field=models.FileField(upload_to='images/barcodes/'),
        ),
    ]
