# Generated by Django 2.2.5 on 2019-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_auto_20190925_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionpicture',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
