# Generated by Django 2.2.5 on 2019-09-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_motionpicture_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motionpicture',
            old_name='checked',
            new_name='approved',
        ),
    ]
