# Generated by Django 2.2.5 on 2019-10-11 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20191010_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default=datetime.date(2019, 10, 11)),
        ),
    ]
