# Generated by Django 2.2.5 on 2019-10-15 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_auto_20191010_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default=datetime.date(2019, 10, 15)),
        ),
    ]
