# Generated by Django 2.2.5 on 2019-10-17 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0006_auto_20191015_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birthday',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='release_date',
            field=models.DateField(default=datetime.date(2019, 10, 17)),
        ),
    ]
