# Generated by Django 2.2.5 on 2019-10-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_auto_20191028_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='motionpicture',
            name='movie_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
